### ISSUE TITLE
Location in planck.js

### ISSUE THREAD

**Issue by zOadT** [zOadT/planck-typescript#4]
Hi @shakiba,

soon I won't be able to work on the definition file for some time, thus I want to add the file to planck.js over the next days.

So the question is: Where shall I put it? Maybe in `./typings/planck.d.ts`?

**Comment by shakiba** [comment]
Awesome, thanks! :)

**Comment by shakiba** [comment]
Awesome, thanks!
I think like this would be great:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by zOadT** [comment]
Ok, so you mean in `./lib/index.d.ts`?

**Comment by shakiba** [comment]
Yes, that sounds perfect! :)

**Comment by zOadT** [comment]
I got a problem. Typescript requires to imort planck explictly in your files to show the typings. So I have to declare it as module. You can still use it as global by `declare var planck: typeof import("planck-js");` in an typings file of your project. Is this okay?

**Comment by zOadT** [comment]
It doesn't work, I have overlooked an Error :(

**Comment by zOadT** [comment]
You can test it on my fork, it works but you have to explictly import `planck-js`. The trick for a global variable doesn't work.

**Comment by zOadT** [comment]
Okay, found a solution. Now, you just have to `import 'planck-js'` in each file or import it once in a `.d.ts` file. I got confused cause my Editor showed errors depending on which files are opened. I will make the PR now.
